targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true # (default)
      # json_serializable:
      #   options:
      #     any_map: false
      #     checked: false
      #     constructor: ""
      #     create_factory: true
      #     create_field_map: false
      #     create_per_field_to_json: false
      #     create_to_json: true
      #     disallow_unrecognized_keys: false
      #     explicit_to_json: false
      #     field_rename: none
      #     generic_argument_factories: false
      #     ignore_unannotated: false
      #     include_if_null: true
