name: drift_crdt
description: An implementation of a drift-based CRDT database, based on the `sqlite_crdt` and `drift` packages.
version: 1.0.9
publish_to: none
# repository: https://github.com/JanezStupar/drift_crdt.git
# homepage: https://janezstupar.com
# issue_tracker: https://github.com/JanezStupar/drift_crdt/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.26.0
  path: ^1.8.0
  crdt: ^5.1.2
  sqlite_crdt:
    git:
      url: https://github.com/Mattertorian/sqlite_crdt.git

dev_dependencies:
  drift_dev: ^2.26.0
  drift_testcases:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/integration_tests/drift_testcases
  test: ^1.22.0
  build_runner: ^2.4.5


# flutter:
#   assets:
#     - test_asset.db
#     - test_asset_migration.db
